color: null
fieldLayouts:
  bb2bc613-6733-4e17-90b3-7dfa3eacd1fc:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-11-12T08:17:33+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 8085ec2a-2bb1-4b93-9c80-a4c2a7ee1f70
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-11-12T08:19:02+00:00'
            elementCondition: null
            fieldUid: 7fcc62cd-904f-4738-abb5-739cfe278b1f # Description
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ea1c6600-baab-4265-81a6-7d959c7691a0
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-11-12T08:39:34+00:00'
            elementCondition: null
            fieldUid: 46cc2cc9-1ebe-41ef-af40-899882c127ef # Categories
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8fd4218f-b4dc-429d-b826-7035fd1a0dbe
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-11-12T13:21:11+00:00'
            elementCondition: null
            fieldUid: d3635528-b99a-4945-85a7-304b466fd1e3 # Price
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9e4a7f16-3cdd-40f9-9d51-251a7cfc3af5
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-11-12T11:48:57+00:00'
            elementCondition: null
            fieldUid: a98f3176-e215-4b47-acff-001465fdfc8a # ItemImage
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e20c0c5d-5c7b-4190-bdbd-268904912f47
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: bfdda906-aa03-4d97-8793-9c02c50e8de5
        userCondition: null
handle: items
hasTitleField: true
icon: ''
name: Items
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
