altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  e934184a-dc02-4728-aecc-cb9e39f265ef:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-11-12T11:44:30+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 10feb8c6-82a3-4884-a9bc-2d0db6909d48
            userCondition: null
            warning: null
            width: 100
          -
            attribute: alt
            class: null
            cols: null
            dateAdded: '2024-11-12T11:52:54+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            instructions: null
            label: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: true
            required: false
            rows: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AltField
            uid: e39a74a8-e8c2-48e0-98fb-8524e6bb6cdd
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: e06eca56-a5a5-4271-b9ae-d7b7fae0f217
        userCondition: null
fs: images
handle: items
name: Items
sortOrder: 1
subpath: items
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
