altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  e8556bb8-0259-41e2-a205-d56b9d266fc0:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-11-12T13:03:14+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 9754ad56-208a-4aed-a1ac-7dbb4a778207
            userCondition: null
            warning: null
            width: 100
          -
            attribute: alt
            class: null
            cols: null
            dateAdded: '2024-11-12T13:04:49+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            instructions: null
            label: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: true
            required: false
            rows: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AltField
            uid: 18884f03-afb1-4042-9efc-1ee3cc8dd14d
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 927cce61-d15c-43de-9fb7-4965a938ca10
        userCondition: null
fs: images
handle: users
name: Users
sortOrder: 2
subpath: users
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
