defaultPlacement: end
enableVersioning: true
entryTypes:
  - a96a970f-c491-425f-b402-25ce2b451181 # Categories
handle: categories
maxAuthors: 1
name: Categories
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  264cfef0-2d06-4198-ab33-71f3b0f593bc: # craft-eindproject
    enabledByDefault: true
    hasUrls: true
    template: categories/_entry.twig
    uriFormat: 'categories/{slug}'
type: channel
